### PR TITLE
monthly hours worked widget

### PR DESCRIPTION
**Pull request by domicode**
display currently worked hours

### CODE REVIEW

**Comment by domicode** [comment]
ready for review

**Comment by koffeinfrei** [comment]
:+1:. Not sure though how accurate this is, as some people don't regularly update the time entries, some even only at the end of the month.

**Comment by domicode** [comment]
it might not be accurate yet but I thought might be some incentive for people to write down their hours more regularly. (I know, high hopes ;-))

**Comment by koffeinfrei** [comment]
very high :smile:

**Pull request merged**
