### PR TITLE
font updates

### PR DESCRIPTION
**Pull request by domicode**

### CODE REVIEW

**Comment by koffeinfrei** [comment]
Looks good now, the font's lines are removed and instead the checkered pattern shows.
I have some suggestions:
- remove the `font-weight`s for `h1` and `h2`, makes it much more readable
- maybe decrease the font sizes overall, such that e.g. the performance tile fits in a single row
- the difference value should be the same font as the main value

**Comment by koffeinfrei** [comment]
Rebased to master.

**Comment by koffeinfrei** [comment]
I updated the font sizes and colors.

The small font in the list widget looks still rugged...

**Comment by domicode** [comment]
The small font looks fine on my display but guess it depends on rendering engine. 

I would put the updated at in black instead of white as it's less relevant in my opinion and if all is white it can look a bit overloaded.

**Comment by koffeinfrei** [comment]
> The small font looks fine on my display but guess it depends on rendering engine.

On mac osx it looks ok yes, on linux it doesn't.

> I would put the updated at in black instead of white as it's less relevant in my opinion and if all is white it can look a bit overloaded.

Updated.

**Comment by domicode** [comment]
for the font problems I would suggest to add a second font which is easier to read in small font sizes but matches the panter font we have for the rest.

**Comment by koffeinfrei** [comment]
> I would suggest to add a second font

If you have one handy sure, but I believe it will be quite a challenge to find a similar font. It doesn't look too bad on linux, so I'd leave this for now.

FF on Linux (Ubuntu):
panter ag dashboard 2015-07-14 22-18-51

**Comment by koffeinfrei** [comment]
:shipit:

**Pull request merged**
